import { iProduct } from "@/types";

// Featured data
export const products: iProduct[] = [
  {
    id: "1",
    name: "Wooden Comfortable Chair",
    category: "Chairs",
    image: [
      "/assets/products/chair-1.jpg",
      "/assets/products/chair-2.jpg",
      "/assets/products/chair-3.jpg",
      "/assets/products/chair-4.jpg",
      "/assets/products/chair-5.jpg",
    ],
    featured: false,
    description:
      "A handcrafted wooden chair designed for comfort and elegance.",
    material: "Premium quality wood, brass fittings",
    length: "30",
    width: "20",
    height: "15",
    weight: "1.5",
    instruction: "Wipe clean with a soft, dry cloth",
  },
  {
    id: "2",
    name: "White Wooden Chair",
    category: "Chairs",
    image: ["/assets/products/chair-a1.jpg", "/assets/products/chair-a2.jpg"],
    featured: true,
    description:
      "A White stylish wooden chair, Highly comfortable sheet with arm rest.",
    material: "Solid oak wood",
    length: "72",
    width: "36",
    height: "30",
    weight: "25",
    instruction: "Wipe clean with a soft, dry cloth",
  },
  {
    id: "3",
    name: "Tranquil Sofa",
    category: "Sofas",
    image: ["/assets/products/sofa-2.jpg", "/assets/products/sofa-1.jpg"],
    featured: true,
    description: "A plush and cozy sofa designed for comfort and style.",
    material: "High-density foam, velvet upholstery",
    length: "80",
    width: "35",
    height: "32",
    weight: "40",
    instruction: "Vacuum regularly, professional cleaning recommended",
  },
  {
    id: "4",
    name: "Elegance Golden Mirror",
    category: "Mirrors",
    image: [
      "/assets/products/mirror-1.jpg",
      "/assets/products/mirror-2.jpg",
      "/assets/products/mirror-3.jpg",
    ],
    featured: true,
    description: "A stylish mirror with lower table space for items.",
    material: "Engineered wood, Resin as table surface.",
    length: "36",
    width: "12",
    height: "72",
    weight: "20",
    instruction: "Dust regularly, avoid exposure to moisture",
  },
  {
    id: "5",
    name: "Royal Coffee Table, Sofa, and Chairs",
    category: "Tables",
    image: [
      "/assets/products/dine-1.jpg",
      "/assets/products/dine-2.jpg",
      "/assets/products/dine-3.jpg",
    ],
    featured: false,
    description:
      "A royal coffee table, sofa, and chairs that complements any interior design.",
    material: "Wood, Silver, and Resin",
    length: "42",
    width: "22",
    height: "18",
    weight: "12",
    instruction: "Clean with a soft cloth, avoid sharp objects",
  },
  {
    id: "6",
    name: "Designed Mirror",
    category: "Mirrors",
    image: ["/assets/products/mirror-b1.jpg"],
    featured: false,
    description: "Silver fascinating embroidery designed mirror.",
    material: "wooden frame",
    length: "90",
    width: "40",
    height: "34",
    weight: "50",
    instruction: "Wipe clean with a soft, dry cloth",
  },
  {
    id: "7",
    name: "Elegant Luxury Mirror with Table",
    category: "Mirrors",
    image: [
      "/assets/products/mirror-a1.jpg",
      "/assets/products/mirror-a2.jpg",
      "/assets/products/mirror-a3.jpg",
    ],
    featured: true,
    description: "A stylish luxury mirror and table with ample space.",
    material: "Solid wood, metal artifacts.",
    length: "18",
    width: "20",
    height: "36",
    weight: "8",
    instruction: "Wipe clean with a soft, dry cloth",
  },
  {
    id: "8",
    name: "Royal Vase Table",
    category: "Tables",
    image: [
      "/assets/products/table-a1.jpg",
      "/assets/products/table-a2.jpg",
      "/assets/products/table-a3.jpg",
      "/assets/products/table-a4.jpg",
      "/assets/products/table-a5.jpg",
    ],
    featured: false,
    description:
      "A small golden color table to keep vases on with ample space.",
    material: "Engineered wood",
    length: "48",
    width: "24",
    height: "30",
    weight: "22",
    instruction: "Dust regularly, wipe with a damp cloth",
  },
  {
    id: "9",
    name: "Golden Table",
    category: "Tables",
    image: ["/assets/products/table-1.jpg", "/assets/products/table-1.jpg"],
    featured: false,
    description: "Golden luxury table to add charm to any space.",
    material: "Golden Embroidery, wooden legs",
    length: "28",
    width: "26",
    height: "32",
    weight: "10",
    instruction: "Dust regularly, avoid water spills",
  },
];

// Testimonials data
export const testimonials = [
  {
    id: 1,
    name: "Manish Suthar",
    role: "Cyber Sec Engineer",
    content:
      "The quality of furniture is exceptional. My clients are always impressed with the craftsmanship and attention to detail.",
    avatar: "https://avatars.githubusercontent.com/u/77256586?v=4",
  },
  {
    id: 2,
    name: "Nitesh Suthar",
    role: "Animator",
    content:
      "We furnished our entire living room with pieces from Mahesh Handicrafts. The furniture is not only beautiful but incredibly comfortable and durable.",
    avatar: "https://avatars.githubusercontent.com/u/122961768?v=4",
  },
  {
    id: 3,
    name: "Harish Suthar",
    role: "Programmer",
    content:
      "As an architect, I appreciate the clean lines and modern aesthetic of Mahesh Handicrafts. It complements my designs perfectly.",
    avatar:
      "https://github.com/harishkumar6375/portfolio/blob/main/IMG_1190.jpg?raw=true",
  },
];
